### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by jackwander** [jackwander/bbc.test#2]
# Task 1
> List of Locations
- [x] Create a table for Locations

**Table name: locations**

Column | Type | Comment
-- | -- | --
location_id | int(10) unsigned Auto Increment |  
city | varchar(191) |  
shortname | varchar(191) |  
created_at | timestamp NULL |  
updated_at | timestamp NULL |  
cover_image | varchar(191) |  

- [x] Create a CRUD for Locations.

**Comment by jackwander** [comment]
# Additional
- [x]  Add Button for Locations
