### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by jackwander** [jackwander/bbc.test#4]
# Task 3
- [x] 1. Create Table for Branches
Table name: branches

Column | Type | Comment
-- | -- | --
branch_id | int(22) Auto Increment |  
bank_id | int(10) |  
location_id | int(10) |  
branch_name | varchar(255) |  
created_at | timestamp NULL |  
updated_at | timestamp NULL |

PRIMARY | branch_id
-- | --
INDEX | location_id
INDEX | bank_id

Source | Target | ON DELETE | ON UPDATE  
-- | -- | -- | --
location_id | locations(location_id) | CASCADE | RESTRICT 
bank_id | banks(bank_id) | CASCADE | RESTRICT 

- [x] 2. Create CRUD for Branches

**Comment by jackwander** [comment]
- [x] 1.a. Add column to **TABLE: branches**

Column | Type 
-- | -- 
status | int(10) 

#### Equivalent number of status
Value | Meaning
-- | --
0 | Offline but Open
1 | Online
2 | Server Down
3 | Closed
