### ISSUE TITLE
Userbranch

### ISSUE THREAD

**Issue by jackwander** [jackwander/bbc.test#5]
# Task 4
- [x] 1. Create Table for Userbranch
Table name: userbranches

Column | Type | Comment
-- | -- | --
userbranch_id | int(11) Auto Increment |  
user_id | int(10) | 
branch_id | int(10) |  
created_at | timestamp NULL |  
updated_at | timestamp NULL |

PRIMARY | userbranch_id
-- | --
INDEX | user_id
INDEX | branch_id

Source | Target | ON DELETE | ON UPDATE  
-- | -- | -- | --
user_id | users(id) | CASCADE | RESTRICT
branch_id | branches(branch_id) | CASCADE | RESTRICT 

- [x] 2. Create CRUD for Users

- [x] 3. Create CRUD for Userbranch
